version: "0.5"
services:
  www:
    build: .
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./public-html:/var/www/html
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8001:80
    environment:
      MYSQL_USER : user
      MYSQL_PASSWORD : test
      MYSQL_ROOT_PASSWORD : test
